---
name: Build & Publish
run-name: Build Podman image and publish on the Container registry
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '@daily'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: rhel-latest
    steps:
      - name: Check Factorio version
        id: get-version
        run: echo "game-version=$(curl https://factorio.com/api/latest-releases | jq .stable.headless -r)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Set Container Registry URL
        id: set-registry-url
        run: |
          echo "registry-url=$(echo $GITHUB_SERVER_URL | sed 's#https\?://##')" >> $GITHUB_OUTPUT
          echo "repository-owner=$(echo ${GITHUB_REPOSITORY_OWNER,,})" >> $GITHUB_OUTPUT
          echo "repository-id=$(echo ${GITHUB_REPOSITORY,,})" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Container
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: ${{ steps.set-registry-url.outputs.image-name }}
          containerfiles: |
            ./Containerfile
          tags: latest
          build-args: |
            VERSION=${{ steps.get-version.outputs.game-version }}

      - name: Push to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ steps.set-registry-url.outputs.registry-url }}/${{ steps.set-registry-url.outputs.repository-owner }}
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
